# Generated by Django 5.2 on 2025-05-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artchill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='image_data',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='canvas',
            name='title',
            field=models.CharField(default='Untitled', max_length=50),
        ),
    ]
