# Generated by Django 5.2 on 2025-05-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artchill', '0002_canvas_image_data_alter_canvas_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='create_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
