# Generated by Django 5.2 on 2025-05-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artchill', '0003_canvas_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canvas',
            name='user',
        ),
    ]
